# Generated by Django 2.0 on 2021-08-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='xyz.jpg', upload_to='userimage/')),
                ('name', models.CharField(default='asd#45', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.IntegerField(default='456')),
            ],
        ),
    ]
