# Generated by Django 2.0 on 2021-08-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='asd#45', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='pas',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
